### ISSUE TITLE
lrogue2 -s segfaults

### ISSUE THREAD

**Issue by runlow** [Elronnd/lrogue#1]
**Expected:**
`lrogue2 -s` or `lrogue2 -s lrogue2.scores` prints the highscore list as suggested [here](https://github.com/moon-chilled/lrogue2/blob/master/src/init.c#L178).

**Observed:**
```
% lrogue2 -s
Segmentation fault (core dumped)
                                %
```
```
% lrogue2 -s ./lrogue2.scores
Segmentation fault (core dumped)
                                %
```

**Comment by moon-chilled** [comment]
Thanks!  Should be fixed now.

**Comment by runlow** [comment]
compiled 68a4fdf and it no longer does that, thank you!
