### ISSUE TITLE
only one score entry in l2rogue2.scores

### ISSUE THREAD

**Issue by runlow** [Elronnd/lrogue#2]
**Expected:**
"Top ten highscores" shows more than one entry - 10 total (as long as all the slots are all filled up of course).

**Observed:**
Only **one** highscore is shown in 68a4fdf. It's the best one but can't see number two, three, etc.

**Steps:**
Start the game a few times and quit it with different amounts of gold.
Notice how the score list never grows beyond one entry. (it should instead have all of your best attempts sorted highest to lowest)

**Comment by runlow** [comment]
When I do...

```
cp lrogue2.scores entry
cat entry >> lrogue2.scores
cat entry >> lrogue2.scores
```
I get:
```
lrogue2 -s

-more-


                              Top  Ten  Rogueists




Rank   Score   Name

 1         0   foo: quit on level 1
 2         0   foo: quit on level 1
 3         0   foo: quit on level 1
```
Shows more than one entry this way. Each entry is 110 bytes. This demonstrates that it *can* show more if the files has more entries.

It seems to me that that it wipes the score file completely in 68a4fdf if you get a highest-yet score - as opposed to adding it to the list while preserving other scores. When your score is not the highest (but still qualifies for top 10) then in 68a4fdf it isn't shown at all (it should be though).

**Comment by runlow** [comment]
This seems to make it a bit better and to work almost as expected:
```diff
diff --git a/src/score.c b/src/score.c
index 71251da..c61eb6e 100644
--- a/src/score.c
+++ b/src/score.c
@@ -173,3 +173,3 @@ void put_scores(object *monster, int other) {
                                if (rogue.gold < s) {
-                                       add_new_score = 0;
+                                       //add_new_score = 0;
                                } else {
```
It still cuts off scores sometimes and not sure yet what the pattern to it is.

**Comment by moon-chilled** [comment]
The score file is meant to show the top 10 _players_, not the top 10 games.

**Comment by runlow** [comment]
I see, didn't realize. Makes more sense then. :thinking:

**Comment by moon-chilled** [comment]
(That being said, multi-user systems are largely dead, so perhaps this behaviour doesn't make sense anymore.)

**Comment by runlow** [comment]
I've read that (about top 10 players) too late and already made a PR thinking it's a bug. Apologies.

I'd imagine that most people (me included) would not run this game on a multi-user system like it used to be done 30 years ago - like you said.

Nevertheless I'm guessing there's good argument in keeping it true to how it used to work and there's the odd chance someone would need this (showing top 10 players rather top 10 of your scores).

Do you think it's worth:
a) changing this default behaviour so that it makes it more useful to users today? (if you think it's a good idea feel free to ignore my PR and add the proper justification in the commit message)
b) offering it as an option somehow?

**Comment by moon-chilled** [comment]
I think it's reasonable even on multi-user systems to allow the same user to have multiple hiscore entries.  If somebody is good enough to take over the entire top 10 list—good for them.  This is also what nethack does.

(436d9d5f8478d0d1647fcb70aa626a2a39868f40)

**Comment by runlow** [comment]
Seems to work. Thank you!
