### ISSUE TITLE
exiting help dialog doesn't redraw level

### ISSUE THREAD

**Issue by runlow** [Elronnd/lrogue#5]
**Expected:**
When you press `?` for help and then `Space` or `Escape` - the level still looks the same way as before pressing it.

**Observed:**
Pressing the `?` doesn't redraw the level upon exiting out of the help dialog.

**Steps:**
1. Start the game
2. Press `?` then `Space`
3. Notice how everything is "gone" but appears again if you go to another room or go downstairs.

**Comment by moon-chilled** [comment]
Can't reproduce.  What terminal, $TERM, and os are you running?

**Comment by runlow** [comment]
Was starting it like this:
`st -f "Liberation Mono:pixelsize=39:charwidth=24" -e rogue`
```
# set|grep TERM
TERM=st-256color
$ uname -r
5.11.12-arch1-1
```
Running it on Archlinux.

When I use the default font the help menu seems to work no problem. I should have checked before reporting. Apologies. Maybe this has to do with the terminal emulator or xft.

`st -f "xos4 Terminus-40" -e lrogue2` seems to work no problem.

**Comment by runlow** [comment]
Closing issue I suppose.

**Comment by runlow** [comment]
Tested it in vt (no Xorg running, no virtualisation) with kernel command line parameters `nomodeset vga=0x202` which result in 80x25 chars mode and it's the same behaviour. Pressing the help key and exiting out of the help message doesn't redraw the level.

Tried it with and without `screen` running and it makes no difference.

To be sure compared it to other linux builds of Stoehr's rogue clone 2 and they were all OK when viewing the help message. Tested:
* [bsdgames-nonfree](https://salsa.debian.org/ucko/bsdgames-nonfree) debian package built on Archlinux
* [this thing](https://coredumpcentral.org/files/linrog37.zip) compiled
* [this project](https://github.com/jonypawks/linuxrogue)

**Comment by runlow** [comment]
Noticed that the status bar **does** get drawn after the help message, just not the level. It must be doing something differently.

Also decided to see what happens if I try to take an "ascii screenshot" (by pressing `X`) when this happens:
```
% cat rogue.screen























Level: 1  Gold: 0      Hp: 12(12)   Str: 16(16) Arm: 4  Exp: 1/0
```

**Comment by runlow** [comment]
Another clue :detective: 

After [this loop](https://github.com/moon-chilled/lrogue2/blob/master/src/instruct.c#L38-L45) the string table `buffer` should be filled up with ascii characters from the level (walls, corridors, floors, etc). When using any of the earlier mentioned setups the bug seems to affect - the string isn't getting filled up.

Hope you don't mind these posts. I'll check it further.

**Comment by runlow** [comment]
Think I almost figured it out.

This solves almost all the problems reported in this issue. One small hickup is that the status bar doesn't disappear during the help dialog but other than that it works perfect:

```diff
diff --git a/src/instruct.c b/src/instruct.c
index c8c3a1e..741c2a0 100644
--- a/src/instruct.c
+++ b/src/instruct.c
@@ -44 +43,0 @@ void Instructions() {
-               clrtoeol();
@@ -49 +47,0 @@ void Instructions() {
-               clrtoeol();
@@ -58 +55,0 @@ void Instructions() {
-               clrtoeol();
@@ -64 +60,0 @@ void Instructions() {
-       clrtoeol();
@@ -67 +62,0 @@ void Instructions() {
-               clrtoeol();
```

Something those setups (the `st` command, the `vga=202` kernel parameter) have in common is that they are all exactly 80 columns wide. Could that have something to do with it? Could this be some ["off-by-one"](https://github.com/moon-chilled/lrogue2/blob/master/src/instruct.c#L35) bug?

Feel free to check/comment whenever you can/want, just reporting.

**Comment by moon-chilled** [comment]
Ah, yes, I see the issue.  It's not an off-by-one, the problem is the cursor was wrapping around and the following line was being cleared before it could be scraped.  Fixed.

**Comment by runlow** [comment]
Compiled 46f78d4cc285521c and it seems to work well. Thank you!
