### ISSUE TITLE
don't prevent save-scumming?

### ISSUE THREAD

**Issue by runlow** [Elronnd/lrogue#8]
I think save-scumming adds replay value because it lets you:
* try out strats on the same game-state
* create snapshots of interesting situations
* yet another thing you can do with the game

At the same time I get that it's not intended by the original devs. That there is a wizard mode (not quite the same though). That part of the appeal of the game is that each run is different from beginning to the end. That it can make competing for score pointless.

Still - it should probably be up to the player whether they want to "cheat" or not, I think.

I removed these in my working-tree as a quick way to allow for save-scumming:
```diff
% git diff -U0
diff --git a/src/save.c b/src/save.c
index 5f1f078..6ce02b1 100644
--- a/src/save.c
+++ b/src/save.c
@@ -127,3 +126,0 @@ void restore(char *fname) {
-       if (new_file_id != saved_file_id) {
-               clean_up("sorry, saved game is not in the same file");
-       }
@@ -161,3 +157,0 @@ void restore(char *fname) {
-       if ((!wizard) && !md_df(fname)) {
-               clean_up("cannot delete file");
-       }
```

Do you think it's wise to have the save-check removed by default?

Do you plan on adding so called "quality of life improvements" or just wanted to clean up some compiler errors to make sure it runs?

**Comment by moon-chilled** [comment]
Not a big fan of save scumming personally, but I don't really like anti-cheat feature, in general.  Will get rid of that tomorrow.

> Do you plan on adding so called "quality of life improvements" or just wanted to clean up some compiler errors to make sure it runs?

I was going to, but . . . life happens.  I might do something, but don't foresee myself making a big time or energy investment.

**Comment by runlow** [comment]
No worries, all good.

**Comment by runlow** [comment]
Build and tested 46f78d4cc285521c

It still [deletes the save file](https://github.com/moon-chilled/lrogue2/blob/master/src/save.c#L141-L143). I don't personally think there's any need for that although you might disagree. I restore the save file from backup.
